version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic &&
             python3 manage.py createsuperuser --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery-worker:
    restart: always
    build:
      context: .
    command: celery -A btc_wallets worker -l info
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A btc_wallets beat -l INFO
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  pgdata:
